# Generated by Django 4.2.5 on 2023-11-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_sellerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('about_product', models.TextField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('authentication_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
    ]
