# Generated by Django 4.2.5 on 2023-11-12 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_category_remove_product_authentication_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_verify',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_category_verify',
            field=models.BooleanField(default=True),
        ),
    ]
