# Generated by Django 4.2.5 on 2023-11-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0011_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_verify',
            field=models.BooleanField(default=True),
        ),
    ]
