# Generated by Django 4.2.5 on 2023-12-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0016_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id_number_info',
            field=models.IntegerField(default=1),
        ),
    ]
