# Generated by Django 4.2.5 on 2023-12-01 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0017_cart_id_number_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='user_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number_info', models.IntegerField(default=1)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
