# Generated by Django 4.2.5 on 2023-12-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0018_alter_cart_cart_verify_user_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id_number_info',
        ),
    ]
