# Generated by Django 4.2.5 on 2023-12-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0020_remove_cart_cart_verify_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
