# Generated by Django 4.2.5 on 2023-12-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0021_cart_items_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_payment',
            name='id_number_info',
        ),
        migrations.AddField(
            model_name='user_payment',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauth.cart'),
        ),
        migrations.AddField(
            model_name='user_payment',
            name='datetime',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='user_payment',
            name='order_id_data',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='user_payment',
            name='payment_id_data',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='user_payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
