# Generated by Django 4.2.5 on 2023-12-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0022_remove_user_payment_id_number_info_user_payment_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_payment',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauth.cart_items'),
        ),
    ]
