# Generated by Django 4.2.5 on 2023-12-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0023_alter_user_payment_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_payment',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauth.cart'),
        ),
    ]
