# Generated by Django 4.2.5 on 2023-12-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0025_alter_user_payment_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='product_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
