# Generated by Django 4.2.5 on 2024-02-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0028_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
