# Generated by Django 4.2.5 on 2024-02-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0029_sellerprofile_latitude_sellerprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='has_updated_password',
            field=models.BooleanField(default=False),
        ),
    ]
