# Generated by Django 4.2.5 on 2024-03-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0030_deliveryboy_has_updated_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=8, unique=True)),
                ('discount_percentage', models.PositiveIntegerField()),
            ],
        ),
    ]
