# Generated by Django 4.2.5 on 2024-03-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0032_coupon_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
