# Generated by Django 4.2.5 on 2024-03-30 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0036_couponused'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.deliveryboy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.user_payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
