# Generated by Django 4.2.5 on 2024-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0039_alter_deliveryassignment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='city',
            field=models.CharField(default='DefaultCity', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='pincode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='state',
            field=models.CharField(default='DefaultState', max_length=20),
        ),
    ]
