# Generated by Django 4.2.5 on 2024-03-31 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0040_deliveryboy_city_deliveryboy_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='userpayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauth.user_payment'),
        ),
    ]
