# Generated by Django 4.2.5 on 2024-03-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0041_remove_order_amount_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
