# Generated by Django 4.2.5 on 2024-03-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0043_remove_deliveryassignment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.deliveryassignment')),
            ],
        ),
    ]
