# Generated by Django 4.2.5 on 2024-04-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0045_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='payment_id_data',
            field=models.TextField(default='empty'),
        ),
    ]
